config/routes.rb
Rails.application.routes.draw do
  # Landing page
  root to: 'auth#landing'

  # Register and login related
    # Github
  get 'github-auth', to: 'github#authorize'
  get 'github-callback', to: 'github#callback'

    # Facebook
  get 'facebook-auth', to: 'facebook#authorize'
  get 'facebook-callback', to: 'facebook#callback'

    # Email
  get 'register', to: 'auth#new'
  post 'register', to: 'auth#register'
  post 'email-auth', to: 'auth#authenticate'
    # Logout
  get 'logout', to: 'application#logout'

  # General user section
  get 'main', to: 'home#main'

    # Problems
  resources :problems, only: [:index, :show]

    # Submission
  resources :submissions, only: [:show, :create]
  post 'problems/:problem_id/submit', to: 'submissions#create', as: 'solve_problem'

    # Contest
  resources :contests, only: [:index, :show]
  get 'contests/join/:id', to: 'contests#join', as: 'join_contest'
  get 'contests/:id/problems', to: 'contests#problems', as: 'contest_problems'

  resources :interviews, only: [] do
    nested do
      get '', action: 'show', as: ''
      get 'auth'
      post 'start'
      post 'finish'
      get 'result'
      post 'logout'
      get 'problems'
      scope 'problems/:problem_id', as: 'problem' do
        get '', action: 'show_problem', as: 'show'
        post 'try', action: 'try_problem', defaults: { format: 'json' }
        post 'solve', action: 'solve_problem'
        get 'result', action: 'submission_result'
      end
    end
  end

  # Admin page
  namespace :admin do
    root 'home#main', as: ''
    resources :problems do
      resources :test_cases, except: [:show]
    end
    resources :contests
    get 'contests/:id/problems', to: 'contests#problems', as: 'contest_problems'
    get 'contests/:id/problems/:problem_id', to: 'contests#show_problem', as: 'contest_show_problem'
    delete 'contests/:id/problems/:problem_id', to: 'contests#delete_problem', as: 'contest_delete_problem'
    post 'contests/:id/problems/:problem_id', to: 'contests#add_problem', as: 'contest_add_problem'
  end

  # Organization page
  namespace :org do
    root 'home#main', as: ''
    resources :company_profiles, only: [:edit, :update]
    resources :interviews do
      resources :interviewees, only: [:index, :new, :create, :show, :destroy]
    end
    get 'interviews/:interview_id/interviewee/:id/problems/:p_id', to: 'interviewees#problem', as: 'interview_interviewee_problem'
    get 'interviews/:interview_id/interviewee/:id/problems/:p_id/result', to: 'interviewees#problem_result', as: 'interview_interviewee_problem_result'
    get 'interviews/:id/problems', to: 'interviews#problems', as: 'interview_problems'
    get 'interviews/:id/problems/:problem_id', to: 'interviews#show_problem', as: 'interview_show_problem'
    delete 'interviews/:id/problems/:problem_id', to: 'interviews#delete_problem', as: 'interview_delete_problem'
    post 'interviews/:id/problems/:problem_id', to: 'interviews#add_problem', as: 'interview_add_problem'
    resources :problems do
      resources :test_cases
    end
  end

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :published_interview_only
  before_action :can_auth, only: [:auth, :start]
  before_action :can_do_problems, except: [:show, :auth, :start, :result, :logout]
  before_action :can_finish, only: [:result, :logout]
  before_action :valid_problem, only: [:show_problem, :try_problem, :solve_problem, :submission_result]

  def show
    @interview = this_interview
  end

  def auth
    @interview = this_interview
    @interviewee = Interviewee.new
  end

  def start
    @interviewee = Interviewee.find_by interviewee_params.merge({interview_id: this_interview.id})
    if @interviewee
      login @interviewee
      @interviewee.interview_result.start
      redirect_to action: :problems
    else
      @interviewee = Interviewee.new email: interviewee_params[:email]
      render :auth
    end
  end

  def problems
    @interview = this_interview
    @problems = @interview.problems
    @submissions = current_interviewee.submissions.index_by &:problem_id
  end

  def show_problem
    @interview = this_interview
    @problem = this_problem
    @submission = last_submission || InterviewSubmission.new(problem: @problem)
  end

  def try_problem
    @submission = InterviewSubmission.new(submission_params)
    @submission.test(secret: false)
    @test_results = @submission.test_results
  end

  def solve_problem
    last = last_submission
    @submission = InterviewSubmission.new(submission_params)
    @submission.author = current_interviewee
    if @submission.process
      last.destroy if last
      redirect_to action: :submission_result
    else
      @interview = this_interview
      @problem = this_problem
      render :show_problem, status: :internal_server_error
    end
  end

  def submission_result
    @interview = this_interview
    @problem = this_problem
    @submission = last_submission
  end

  def finish
    current_interviewee.interview_result.finish
    redirect_to action: :result
  end

  def result
    @interviewee = current_interviewee
  end

  def logout
    clear
    redirect_to action: :show
  end

  protected
  def published_interview_only
    render file: 'public/404' unless this_interview.published?
  end

  def can_auth
    if (interviewee? && of_this_interview?)
      redirect_to action: :problems if !current_interviewee.interview_result.finished?
      redirect_to action: :result if current_interviewee.interview_result.finished?
    end
  end

  def can_do_problems
    if (interviewee? && of_this_interview?)
      redirect_to action: :result if current_interviewee.interview_result.finished?
    else
      redirect_to action: :auth
    end
  end

  def can_finish
    if (interviewee? && of_this_interview?)
      redirect_to action: :problems unless current_interviewee.interview_result.finished?
    else
      redirect_to action: :auth
    end
  end

  def valid_problem
    raise ActiveRecord::RecordNotFound.new unless this_problem.of? this_interview    
  end

  private
  def this_interview
    Interview.friendly.find(params[:interview_id])
  end

  def this_problem
    Problem.find(params[:problem_id])
  end

  def last_submission
    InterviewSubmission.find_by(problem: this_problem, author: current_interviewee)
  end

  def submission_params
    params.require(:submission).permit(:problem_id, :language_id, :content)
  end

  def interviewee?
    session[:interviewee_id] && Interviewee.find_by(id: session[:interviewee_id])
  end

  def of_this_interview?
    current_interviewee.interview == this_interview
  end

  def interviewee_params
    params.require(:interviewee)
      .permit :email, :password
  end

  def current_interviewee
    Interviewee.find_by(id: session[:interviewee_id])
  end

  def login interviewee
    session[:interviewee_id] = interviewee.id
  end

  def clear
    session.delete :interviewee_id
    @current_interviewee = nil
  end

end

app/controllers/org/company_profiles_controller.rb
class Org::CompanyProfilesController < Org::OrganizationController
  CompanyProfile = ::CompanyProfile

  before_action :authority_check

  def edit
    @company = this_company
  end

  def update
    company = this_company
    if company.update company_params
      redirect_to org_path
    else
      @company = company
      render :edit
    end
  end

  private
  def this_company
    CompanyProfile.find(params[:id])
  end

  def company_params
    params[:company_profile]
      .permit :name
  end

  def authority_check
    render file: 'public/404' unless this_company.owner == current_user
  end
end

app/controllers/org/home_controller.rb
class Org::HomeController < Org::OrganizationController
  def main
    @company = current_company
  end

  private
  def current_company
    if company = current_user.company_profile
      company
    else
      company = CompanyProfile.new(owner_id: current_user.id)
      company.save
      company
    end
  end
end

app/controllers/org/interviewees_controller.rb
class Org::IntervieweesController < Org::OrganizationController
  before_action :authority_check
  before_action :valid_container_check, only: [:show, :problem, :problem_result]
  before_action :valid_container_for_problem_check, only: [:problem, :problem_result]

  def index
    @interviewees = Interviewee.belongs_to_interview this_interview
    @interview = this_interview
  end

  def new
    @interviewee = Interviewee.new
    @interview = this_interview
  end

  def create
    @interviewee = Interviewee.create interviewee_params
    @interview = this_interview
    @interviewee.interview = this_interview
    if @interviewee.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
    @interview = this_interview
    @interviewee = this_interviewee
    @interview_result = @interviewee.interview_result
    @problems = @interview.problems
    @submissions = @interviewee.submissions.index_by &:problem_id
  end

  def problem
    @interview = this_interview
    @problem = this_problem
    @interviewee = this_interviewee
  end

  def problem_result
    @interview = this_interview
    @problem = this_problem
    @interviewee = this_interviewee
    @submission = @interviewee.submissions.find_by({problem_id: @problem.id})
  end

  def destroy
    Interviewee.destroy params[:id]
    redirect_to action: :index
  end

  private
  def this_interview
    Interview.friendly.find(params[:interview_id])
  end

  def this_interviewee
    Interviewee.find(params[:id])
  end

  def interviewee_params
    params.require(:interviewee)
      .permit :email
  end

  def this_problem
    Problem.find(params[:p_id])
  end

  def authority_check
    render file: 'public/404' unless this_interview.owner == current_user
  end

  def valid_container_check
    render file: 'public/404' unless this_interviewee.of? this_interview
  end

  def valid_container_for_problem_check
    render file: 'public/404' unless this_problem.of? this_interview
  end
end

app/controllers/org/interviews_controller.rb
class Org::InterviewsController < Org::OrganizationController
  Interview = ::Interview
  before_action :authority_check, except: [:index, :new, :create]
  before_action :valid_container_check, only: [:delete_problem]

  def index
    @interviews = Interview.of current_user
  end

  def new
    @interview = Interview.new
  end

  def create
    @interview = Interview.new(interview_params)
    @interview.owner = current_user
    if @interview.save
      redirect_to action: :show, id: @interview.friendly_id
    else
      render :new
    end
  end

  def show
    @interview = this_interview
  end

  def edit
    @interview = this_interview
  end

  def update
    @interview = this_interview
    if @interview.update interview_params
      redirect_to action: :show, id: @interview.friendly_id
    else
      render :edit
    end
  end

  def problems
    @interview = this_interview
    @problems = this_interview.problems
    @available = Problem.available.belong_to_user current_user
  end

  def show_problem
    @interview = this_interview
    @problem = this_problem
    render :problem
  end

  def add_problem
    if this_problem.ready? && this_interview.draft?
      this_interview.problems << this_problem
    end
    redirect_to action: :problems
  end

  def delete_problem
    this_interview.problems.delete this_problem unless this_interview.published?
    redirect_to action: :problems
  end

  def destroy
    this_interview.problems.delete_all
    Interview.friendly.destroy params[:id]
    redirect_to action: :index
  end

  private
  def this_interview
    Interview.friendly.find(params[:id])
  end

  def this_problem
    Problem.find(params[:problem_id])
  end

  def interview_params
    params[:interview]
      .permit :title, :description, :salary_min, :salary_max, :duration, :status
  end

  def authority_check
    render file: 'public/404' unless this_interview.owner == current_user
  end

  def valid_container_check
    render file: 'public/404' unless this_problem.of? this_interview
  end
end

app/controllers/org/organization_controller.rb
class Org::OrganizationController < ApplicationController
  before_action :org_only
end

app/controllers/org/problems_controller.rb
class Org::ProblemsController < Org::OrganizationController
  Problem = ::Problem

  before_action :authority_check, only: [:show, :edit, :update, :destroy]
  before_action :unpublished_problem_check, only: [:edit, :update, :destroy]

  def index
    @draft = Problem.draft.belong_to_user current_user
    @available = Problem.available.belong_to_user current_user
    @published = Problem.published.belong_to_user current_user
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(problem_params)
    @problem.author = current_user
    if @problem.save
      redirect_to action: :show, id: @problem.id
    else
      render :new
    end
  end

  def show
    @problem = this_problem
  end

  def edit
    @problem = this_problem
  end

  def update
    @problem = this_problem
    if @problem.update problem_params
      redirect_to action: :show, id: @problem.id
    else
      render :edit
    end
  end

  def destroy
    Problem.destroy params[:id]
    redirect_to action: :index
  end

  private
  def this_problem
    Problem.find(params[:id])
  end

  def problem_params
    params.require(:problem).permit(:title, :max_points, :description, :status,
                                    :problem_type_id, :level_id, :sample_input,
                                    :sample_output, :explanation,
                                    domain_ids: [], language_ids: [])
  end

  def authority_check
    render file: 'public/404' unless this_problem.author == current_user
  end

  def unpublished_problem_check
    redirect_to action: :show if this_problem.published?
  end
end

app/controllers/org/test_cases_controller.rb
class Org::TestCasesController < Org::OrganizationController
  Problem = ::Problem
  TestCase = ::TestCase

  before_action :authority_check, only: [:show, :edit, :update, :destroy]
  before_action :valid_container_check, only: [:show, :edit, :update, :destroy]
  before_action :unpulished_problem_check, only: [:new, :create, :edit, :update, :destroy]

  def index
    @problem = this_problem
    @test_cases = this_problem.test_cases
  end

  def new
    @problem = this_problem
    @test_case = TestCase.new
  end

  def create
    @problem = this_problem
    @test_case = TestCase.new(test_case_params)
    @test_case.problem = @problem
    if @test_case.save
      redirect_to action: :index, problem_id: @problem.id
    else
      render :new
    end
  end

  def show
    @problem = this_problem
    @test_case = this_test_case
  end

  def edit
    @problem = this_problem
    @test_case = this_test_case
  end

  def update
    @problem = this_problem
    @test_case = this_test_case
    if @test_case.update test_case_params
      redirect_to action: :index, problem_id: @problem.id
    else
      render :edit
    end
  end

  def destroy
    TestCase.destroy this_test_case
    redirect_to action: :index, problem_id: params[:problem_id]
  end

  private
  def this_problem
    Problem.find(params[:problem_id])
  end

  def this_test_case
    TestCase.find(params[:id])
  end

  def test_case_params
    params.require(:test_case)
      .permit(:problem_id, :input, :output, :max_time, :secret)
  end

  def unpulished_problem_check
    redirect_to action: :index if this_problem.published?
  end

  def authority_check
    render file: 'public/404' unless this_test_case.author == current_user
  end

  def valid_container_check
    render file: 'public/404' unless this_test_case.of? this_problem
  end
end

app/helpers/interview_helper.rb
module InterviewHelper
  def interview_allowed_statuses
    Interview.statuses.keys.to_a
  end

  def interview_url interview
    "#{custom_config.domain}/interviews/#{interview.friendly_id}"
  end

  def company_name_of interview
    interview.owner.company_profile.name if interview.owner.company_profile
  end

  def interview_submission_status submission
    if submission && submission.score == submission.problem.max_points
      "DONE"
    else
      "NOT DONE"
    end
  end

  def interview_submission_status_class submission
    if submission
      if submission.score == submission.problem.max_points
        "label-info"
      else
        "label-default"
      end
    else
      "label-danger"
    end
  end

  def interview_submission_score submission, problem
    score_text = sprintf('%d / %d', submission ? submission.score : 0, problem.max_points)
    link_to_if(submission, score_text, interview_problem_result_path(@interview, problem))
  end

  def org_interview_submission_score submission, problem
    score_text = sprintf('%d / %d', submission ? submission.score : 0, problem.max_points)
    link_to_if(submission, score_text, org_interview_interviewee_problem_result_path(@interview, @interviewee, problem))
  end
end

app/views/org/interviews/_form.html.erb
<%= form_for([:org, interview]) do |f| %>
  <div class="form-group row">
    <%= f.label :title, class: "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, class: "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <div id="description-editor" class="form-control markdown-text" data-ace-mode="markdown" data-ace-for="interview_description"><%= interview.description %></div>
      <%= f.hidden_field :description %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :salary_min, 'Min Salary (USD)', class: "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.number_field :salary_min, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :salary_max, 'Max Salary (USD)', class: "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.number_field :salary_max, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :duration, 'Duration (minutes)', class: "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.number_field :duration, class: "form-control" %>
    </div>
  </div>
  <% if can_change_status? interview %>
  <div class="form-group row">
    <%= f.label :status, class: "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.select :status, interview_allowed_statuses, class: "form-control" %>
    </div>
  </div>
  <% end %>
  <div class="form-group row">
    <div class="col-xs-9 col-xs-offset-3">
      <%= f.submit 'Submit Interview', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/org/interviews/edit.html.erb
<%= render 'form', interview: @interview %>
<br>
<%= link_to 'Interviews', org_interviews_path %>

app/views/org/interviews/index.html.erb
<h1>Organization Interviews</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
	<tr>
		<td>Interviews</td>
    <td>Status</td>
    <td>Share Url</td>
    <td>Manage Problems</td>
    <td>Manage Interviewee</td>
	</tr>
    <% @interviews.each do |interview| %>
      <tr>
        <td><%= link_to interview.title, org_interview_path(interview) %></td>
        <td><span class="label label-info"><%= interview.status %></span></td>
        <td><%= interview_url interview %></td>
        <td><%= link_to 'Problems', org_interview_problems_path(interview) %></td>
        <td><%= link_to 'Interviewees', org_interview_interviewees_path(interview) %></td>
        <td><%= link_to 'Delete', [:org, interview], method: :delete, data: {confirm: 'Are you sure'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Interview', new_org_interview_path %><br>
<%= link_to 'Back', org_path %>

app/views/org/interviews/new.html.erb
<h1>New Org Interview</h1>

<%= render 'form', interview: @interview %>
<br>
<%= link_to 'Back', org_interviews_path %>

app/views/org/interviews/problem.html.erb
<%= render 'problems/details', problem: @problem %>
<hr>
<%= link_to 'Back', org_interview_problems_path(@interview) %>

app/views/org/interviews/problems.html.erb
<h1>Interview Problems</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
	<tr>
		<td>In Interview Problems</td>
	</tr>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= link_to problem.title, org_interview_show_problem_path(@interview, problem) %></td>
        <td><%= link_to 'Delete', org_interview_delete_problem_path(@interview, problem), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
	<tr>
		<td>Available Problems</td>
	</tr>
    <% @available.each do |problem| %>
      <tr>
        <td><%= link_to problem.title, org_interview_show_problem_path(@interview, problem) %></td>
        <td><%= link_to 'Add', org_interview_add_problem_path(@interview, problem), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', org_interviews_path %>

app/views/org/interviews/show.html.erb
<%= render 'interviews/details', interview: @interview %>

<p>
<%= link_to 'Problems', org_interview_problems_path(@interview) %> |
<%= link_to 'Interviewees', org_interview_interviewees_path(@interview) %>
</p>
<p>
<%= link_to 'Interviews', org_interviews_path %> |
<%= link_to 'Edit', edit_org_interview_path(@interview) %>
</p>